### PR TITLE
Switch for limited Tyr functionality on private repos.

### LINKED ISSUE #157: Cannot integrate with private repositories
Private repositories need authorization token in parameters when performing communication with GitHub API.

error: https://pastebin.com/Xsh5BDeW

### PR DESCRIPTION
**Pull request by xvanick1**
Added switch for the limited Tyr functionality on private repos with unchanged scope of oauth token permissions.
Readme updated.

Resolves #157

### CODE REVIEW

File: tyr-core/src/main/java/org/jboss/tyr/check/SkipCheck.java [hunk 1]
```diff
@@ -37,6 +37,9 @@ public boolean shouldSkip(JsonObject payload, FormatYaml config) throws InvalidP
         if (payload == null || config == null) {
             throw new IllegalArgumentException("Input arguments cannot be null");
         }
+        if (gitHubService.commitCheckDisabled()) {
```
Comment (xstefank) [inline tyr-core/src/main/java/org/jboss/tyr/check/SkipCheck.java:40]: come on, you can write this conditional into the existing if ;)

File: tyr-core/src/main/java/org/jboss/tyr/check/TemplateChecker.java [hunk 2]
```diff
@@ -128,9 +128,11 @@ public String checkPR(JsonObject payload) throws InvalidPayloadException {
                     format.getDescription().getOptionalRows()));
         }
 
-        if (format.getCommit() != null) {
-            commitMessagesCheck.setRegex(format.getCommit());
-            checks.add(commitMessagesCheck);
+        if (!configuration.disableCommitCheck()){
+            if (format.getCommit() != null) {
```
Comment (xstefank) [inline tyr-core/src/main/java/org/jboss/tyr/check/TemplateChecker.java:132]: also doesn't need an inner if statement

File: tyr-core/src/main/java/org/jboss/tyr/config/TyrConfiguration.java [hunk 3]
```diff
@@ -23,6 +23,9 @@
     @ConfigProperty(name = "github.status.push", defaultValue = "true")
     boolean statusPush();
 
+    @ConfigProperty(name = "github.commit.check.disable", defaultValue = "false")
```
Comment (xstefank) [inline tyr-core/src/main/java/org/jboss/tyr/config/TyrConfiguration.java:26]:
```suggestion
    @ConfigProperty(name = "github.commit.check.disabled", defaultValue = "false")
```

File: tyr-core/src/main/java/org/jboss/tyr/config/TyrConfiguration.java [hunk 4]
```diff
@@ -23,6 +23,9 @@
...
+    boolean disableCommitCheck();
```
Comment (xstefank) [inline tyr-core/src/main/java/org/jboss/tyr/config/TyrConfiguration.java:27]: better to align this with the property name so 
```suggestion
    boolean commitCheckDisabled();
```

File: tyr-core/src/main/java/org/jboss/tyr/github/GitHubService.java [hunk 5]
```diff
@@ -49,6 +49,10 @@
     @Inject
     TyrConfiguration configuration;
 
+    public boolean commitCheckDisabled() {
```
Comment (xstefank) [inline tyr-core/src/main/java/org/jboss/tyr/github/GitHubService.java:52]: is this wrapper needed? Can't you access configuration when you need it?

**Review by xstefank — CHANGES_REQUESTED** [review]

File: tyr-core/src/main/java/org/jboss/tyr/github/GitHubService.java (hunk 5 above)
Comment (xvanick1) [reply tyr-core/src/main/java/org/jboss/tyr/github/GitHubService.java:52]: Unfortunately I wasn't able to access the configuration differently without a need of extensive changes to the existing SkipCheck Tests. Also don't wanted to inject TemplateChecker, from where I could access the required method. Because of that I've made this small workaround wrapper.

File: tyr-core/src/main/java/org/jboss/tyr/check/TemplateChecker.java (hunk 2 above)
Comment (xvanick1) [reply tyr-core/src/main/java/org/jboss/tyr/check/TemplateChecker.java]: Had to merge them, because the tests started to fail.

File: tyr-core/src/main/java/org/jboss/tyr/github/GitHubService.java (hunk 5 above)
Comment (xvanick1) [reply tyr-core/src/main/java/org/jboss/tyr/github/GitHubService.java]: Implemented fix based on recommendation.

File: tyr-core/src/main/java/org/jboss/tyr/check/SkipCheck.java (hunk 1 above)
Comment (xvanick1) [reply tyr-core/src/main/java/org/jboss/tyr/check/SkipCheck.java]: Implemented fix based on recommendation.

File: README.md [hunk 6]
```diff
@@ -63,6 +63,21 @@ green color, and in terminal where the server runs you’ll see
...
+1. Repeat the **3rd step**, point **i.** of the Development Guide, but tick the "repo" instead of "repo:status".
+1. Generate this new token and use it.
+> Because GitHub has improperly set OAuth token permissions for private repos vs. public repos, we have to extend the scope of permissions for the private repos, so the whole functionality of Tyr can be guaranteed.
+
+If this is not suitable for you, then you can use the alternative configuration of Tyr. 
+This means that Tyr will work on your private repo with default permissions, but with limited functionality.
+
+1. Repeat the **3rd step** of the Development Guide but use also property `tyr.github.commit.check.disable` with its value set to true.   
+Alternatively:
+1. Repeat the **7th step** of the development Guide and delete all the parts of the file where commit occurs.
```
[the remark this answers is not in the document]
Comment (xvanick1) [reply README.md]: Implemented fix based on recommendation.

File: README.md [hunk 7]
```diff
@@ -63,6 +63,21 @@ green color, and in terminal where the server runs you’ll see
...
    > If not, check Tyr output for any Exceptions. Also check incoming ngrok HTTP requests to determine error code. Try to rebuild and rerun Tyr. Check GitHub if token was used by Tyr. Check latest info at the bottom of your test-repo webhook settings.
 
+### Is your test repository private?
+If yes, some changes have to done in the configuration.  
+
+1. Repeat the **3rd step**, point **i.** of the Development Guide, but tick the "repo" instead of "repo:status".
+1. Generate this new token and use it.
+> Because GitHub has improperly set OAuth token permissions for private repos vs. public repos, we have to extend the scope of permissions for the private repos, so the whole functionality of Tyr can be guaranteed.
+
+If this is not suitable for you, then you can use the alternative configuration of Tyr.
```
[the remark this answers is not in the document]
Comment (xvanick1) [reply README.md]: Reformulated whole new part of README.

File: README.md [hunk 8]
```diff
@@ -63,6 +63,25 @@ green color, and in terminal where the server runs you’ll see
 **Status update: 201**. 
    > If not, check Tyr output for any Exceptions. Also check incoming ngrok HTTP requests to determine error code. Try to rebuild and rerun Tyr. Check GitHub if token was used by Tyr. Check latest info at the bottom of your test-repo webhook settings.
 
+### Is your test repository private?
```
Comment (xstefank) [inline README.md:66]:
```suggestion
### Is your repository private?
```

File: tyr-core/src/main/java/org/jboss/tyr/config/TyrConfiguration.java [hunk 9]
```diff
@@ -23,6 +23,9 @@
     @ConfigProperty(name = "github.status.push", defaultValue = "true")
     boolean statusPush();
 
+    @ConfigProperty(name = "github.commit.check.disabled", defaultValue = "false")
```
Comment (xstefank) [inline tyr-core/src/main/java/org/jboss/tyr/config/TyrConfiguration.java:26]:
```suggestion
    @ConfigProperty(name = "github.commit.checks.disabled", defaultValue = "false")
```
There might be more commit checks in future (almost for sure will be :D)

File: tyr-core/src/main/java/org/jboss/tyr/config/TyrConfiguration.java [hunk 10]
```diff
@@ -23,6 +23,9 @@
...
+    boolean commitCheckDisabled();
```
Comment (xstefank) [inline tyr-core/src/main/java/org/jboss/tyr/config/TyrConfiguration.java:27]:
```suggestion
    boolean commitChecksDisabled();
```

**Review by xstefank — CHANGES_REQUESTED** [review]
looks good, just a small naming correction

File: README.md (hunk 8 above)
Comment (xvanick1) [reply README.md]: Implemented fix based on recommendation.

File: tyr-core/src/main/java/org/jboss/tyr/config/TyrConfiguration.java (hunk 9 above)
Comment (xvanick1) [reply tyr-core/src/main/java/org/jboss/tyr/config/TyrConfiguration.java]: Implemented fix based on recommendation.

File: tyr-core/src/main/java/org/jboss/tyr/config/TyrConfiguration.java (hunk 10 above)
Comment (xvanick1) [reply tyr-core/src/main/java/org/jboss/tyr/config/TyrConfiguration.java]: Implemented fix based on recommendation.

**Review by xstefank — APPROVED** [review]

**Comment by xstefank** [comment]
I only miss some testing that would simulate the private repository invocations. However, we will do this in a follow up PR. Merging, thanks!
